feat: ko should allow building non-root module
mesosphere/dispatch-catalog pull request #26
Opened 2020-07-10 13:17 UTC by mhrabovcin

Adds new features to `ko` function:

- Allow specifying environment variables. That is useful when `GITHUB_TOKEN` is need in order to build `go` projects that are referencing private modules
- Adds `working_dir` argument that allows building projects that consist of multiple go modules within a single repository.

2020-07-13 10:06 UTC, armandgrillet approved these changes
LGTM, was this tested?

2020-07-13 10:08 UTC, mhrabovcin commented
@armandgrillet it is part of konvoy PR - https://github.com/mesosphere/konvoy/pull/1792 and builds are passing.

2020-07-13 17:38 UTC, orsenthil approved these changes
LGTM.

2020-07-13 17:38 UTC, orsenthil commented
@chhsia0  / @jbarrick-mesosphere  - please review and merge.

2020-07-21 16:04 UTC, chhsia0 requested changes
Overall LGTM w/ a minor suggestion. Thanks!

2020-07-21 16:04 UTC, chhsia0 commented on starlark/experimental/go.star
> +            workingDir=build_working_dir,
Could you add a `join` function in `starlark/stable/path.star` and use it here?

```python
def join(path, *paths):
    """Join two or more path components, inserting '/' as needed.
    If any component is an absolute path, all previous path components
    will be discarded."""

    for p in paths:
        if p.startswith("/"):
            path = p
        elif p != "":
            path += ("" if path == "" or path.endswith("/") else "/") + p
    return path
```
Then use it here as `workingDir=join(git_checkout_dir(git_name), working_dir)`?
If so, you could default `working_dir` to `""`, and remove the `build_working_dir` above.

2020-07-21 16:04 UTC, chhsia0 commented on starlark/stable/go.star
> +            workingDir=build_working_dir,
Ditto.

2020-07-22 07:19 UTC, mhrabovcin commented
@chhsia0 thanks for the feedback. I've added a new `join` function.

2020-07-22 14:31 UTC, chhsia0 approved these changes

2020-07-22 14:31 UTC, merged