Add new generate_version method to pipeline
mesosphere/dispatch-catalog pull request #27
Opened 2020-07-17 18:28 UTC by jbarrick-mesosphere

Upstreaming this from our mesosphere/dispatch Dispatchfile so others can use it.

2020-07-21 18:26 UTC, chhsia0 requested changes

2020-07-21 18:26 UTC, chhsia0 commented on starlark/stable/pipeline.star
> +def generate_version(git, name):
How about moving this function to `git.star`?

2020-07-22 14:34 UTC, chhsia0 approved these changes
LGTM. I forgot that moving things around might introduce backward incompatibility. But for users to use `generate_version` they have to update the load statement so it's probably fine.

2020-07-22 18:06 UTC, jbarrick-mesosphere commented
Yeah it should be okay since we recommend users pin to a tag.

2020-07-22 18:22 UTC, merged